- name: PostgreSQL ユーザー作成
  become: yes
  become_user: postgres
  postgresql_user:
    name=redmine
    password={{ db_passwd_redmine }}

- name: PostgreSQL データベース作成
  become: yes
  become_user: postgres
  postgresql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
